[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Managing Underperforming Teams Across Cultures: Strategies for Building Cultural Competence and Understanding"
